### ISSUE TITLE
Crafting 

### ISSUE THREAD

**Issue by Darknessko** [Zzeyy/ZEEGAMES-RP#1]
Spravil by som to že by som dal do NPC aut a odpadových kôš také USBčka ktoré keď hackneš tak dostaneš nejaké veci napr. Biele usb-trava semienko, šierne-náboje, fialove-gun atačmenty a tak podobne.

**Comment by Zzeyy** [comment]
Prozatím zvažuji, že bych přidal náhodný loot do košů a případně na další místa,
ale něco takového by se velice prodražilo a hlavně by to stálo hodně času.
