### ISSUE TITLE
Dát že když někoho uneseme a bdueme chtít gross tak že stačí když bude souhlasit většina třeba když nás tam bude 7 tak že to odsouhlasí 4 lidi

### ISSUE THREAD

**Issue by DemaxCz** [Zzeyy/ZEEGAMES-RP#2]
**Pokud se na tvůj návrh nového obsahu váže nějaký problém, popiš ho.**
Rozepiš se, čím víc informací máme, tím rychleji bude problém vyřešen.

**Popiš, co přesně má nový obsah přinést.**
Co by sis přál nového na server, co přesně to má být.

**Existují nějaké alternativní možnosti?**
Je i něco jiného, co bychom mohli udělat, abychom naplnili tvůj návrh?

**Comment by Zzeyy** [comment]
Toto se stane novým pravidlem.
